# Generated by packaging/homebrew/render.sh — do not edit by hand.
cask "mq-bridge" do
  version "0.4.9"
  sha256 "2d701ce98a9dd273f657a29fa363aa64ca691bdeb148ac7627ebfd7e45663859"

  url "https://github.com/marcomq/mq-bridge/releases/download/v0.4.9/mq-bridge_0.4.9_aarch64.dmg"
  name "mq-bridge"
  desc "Desktop UI for mq-bridge — universal message and data bridge"
  homepage "https://github.com/marcomq/mq-bridge"

  depends_on arch: :arm64

  app "mq-bridge.app"

  zap trash: [
    "~/Library/Application Support/com.marcomq.mqbridgeapp",
    "~/Library/Caches/com.marcomq.mqbridgeapp",
    "~/Library/Preferences/com.marcomq.mqbridgeapp.plist",
    "~/Library/Saved Application State/com.marcomq.mqbridgeapp.savedState",
  ]
end
