# Generated by packaging/homebrew/render.sh — do not edit by hand.
cask "mq-bridge" do
  version "0.2.12"
  sha256 "8b8f37b88d65d7b65f9a669591fa9deae2e2b1827984615f47d6683ebeecaec7"

  url "https://github.com/marcomq/mq-bridge-app/releases/download/0.2.12/mq-bridge_0.2.12_aarch64.dmg"
  name "mq-bridge"
  desc "Desktop UI for mq-bridge — universal message and data bridge"
  homepage "https://github.com/marcomq/mq-bridge-app"

  depends_on arch: :arm64

  app "mq-bridge.app"

  zap trash: [
    "~/Library/Application Support/com.marcomq.mqbridgeapp",
    "~/Library/Caches/com.marcomq.mqbridgeapp",
    "~/Library/Preferences/com.marcomq.mqbridgeapp.plist",
    "~/Library/Saved Application State/com.marcomq.mqbridgeapp.savedState",
  ]
end
