# Generated by packaging/homebrew/render.sh — do not edit by hand.
cask "mq-bridge" do
  version "0.4.13"
  sha256 "4ad463dfb84590c2048401520ab57f9a22cdc97b3463686ab7d3cc8bd5c2ad32"

  url "https://github.com/marcomq/mq-bridge/releases/download/v0.4.13/mq-bridge_0.4.13_aarch64.dmg"
  name "mq-bridge"
  desc "Desktop UI for mq-bridge — universal message and data bridge"
  homepage "https://github.com/marcomq/mq-bridge"

  depends_on arch: :arm64

  app "mq-bridge.app"

  zap trash: [
    "~/Library/Application Support/com.marcomq.mqbridgeapp",
    "~/Library/Caches/com.marcomq.mqbridgeapp",
    "~/Library/Preferences/com.marcomq.mqbridgeapp.plist",
    "~/Library/Saved Application State/com.marcomq.mqbridgeapp.savedState",
  ]
end
