# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh in marcomq/mq-bridge-pulsar — do not edit by hand.
class MqBridgePulsar < Formula
  desc "Apache Pulsar endpoint plugin for mq-bridge"
  homepage "https://github.com/marcomq/mq-bridge-pulsar"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/marcomq/mq-bridge-pulsar/releases/download/0.1.5/mq-bridge-pulsar-0.1.5-aarch64-apple-darwin.tar.gz"
      sha256 "dda72643096d7d4e76bf30127d1240538a10b0c5df6120432cba8914db6d9b9c"
    end
    on_intel do
      url "https://github.com/marcomq/mq-bridge-pulsar/releases/download/0.1.5/mq-bridge-pulsar-0.1.5-x86_64-apple-darwin.tar.gz"
      sha256 "4c8b8c11ff52462ebcc0326a213763729e4f3b3c79ca07571b5cc9b54082b516"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcomq/mq-bridge-pulsar/releases/download/0.1.5/mq-bridge-pulsar-0.1.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d37850458fce9bf204b9c45788a8cb424590bdddd3ccd26aff01870b7439ea6a"
    end
    on_arm do
      url "https://github.com/marcomq/mq-bridge-pulsar/releases/download/0.1.5/mq-bridge-pulsar-0.1.5-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "384999250fc240fe97140120c004298e1185cb867f500320f06e4ee8ba78fd86"
    end
  end

  def install
    # $HOMEBREW_PREFIX/lib/mq-bridge is on mq-bridge's plugin search path.
    (lib/"mq-bridge").install Dir["libmq_bridge_pulsar.*"]
  end

  test do
    ext = OS.mac? ? "dylib" : "so"
    assert_predicate lib/"mq-bridge/libmq_bridge_pulsar.#{ext}", :exist?
  end
end
