# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh in marcomq/mq-bridge-connect — do not edit by hand.
class MqBridgeConnect < Formula
  desc "Unofficial Redpanda Connect compatibility plugin for mq-bridge"
  homepage "https://github.com/marcomq/mq-bridge-connect"
  version "0.2.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/marcomq/mq-bridge-connect/releases/download/v0.2.0/mq-bridge-connect-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "c74f382f1f297130a7c80f11ab160a8db5c27e475b5fdf89ff7b6f7747353947"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcomq/mq-bridge-connect/releases/download/v0.2.0/mq-bridge-connect-0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "486c2966c97cc64b119feb132ff9182665cc961f5b2a0119ec40c2388df7fd64"
    end
    on_arm do
      url "https://github.com/marcomq/mq-bridge-connect/releases/download/v0.2.0/mq-bridge-connect-0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ba9c5553f61c0ac6a43326567f2d71f1c57a073420e9ff98061c3e314762d3b1"
    end
  end

  def install
    # Both libraries share one directory: the plugin loads its Go sibling from
    # beside itself. $HOMEBREW_PREFIX/lib/mq-bridge is on mq-bridge's search path.
    (lib/"mq-bridge").install Dir["libmq_bridge_connect*"]
    doc.install "THIRD_PARTY_NOTICES", "LICENSE-MIT", "LICENSE-APACHE", "INSTALL.md"
  end

  test do
    ext = OS.mac? ? "dylib" : "so"
    assert_predicate lib/"mq-bridge/libmq_bridge_connect.#{ext}", :exist?
    assert_predicate lib/"mq-bridge/libmq_bridge_connect_go.#{ext}", :exist?
    assert_predicate doc/"THIRD_PARTY_NOTICES", :exist?
  end
end
