# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh — do not edit by hand.
class MqBridgeApp < Formula
  desc "Universal, protocol-agnostic message and data bridge (CLI + MCP server)"
  homepage "https://github.com/marcomq/mq-bridge"
  version "0.4.11"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/marcomq/mq-bridge/releases/download/v0.4.11/mq-bridge-cli-aarch64-apple-darwin.tar.gz"
      sha256 "59f75f14331302a9150c8424a2b91b450b4fabf85ecdb9e4a2cdbe89ef16e4b8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcomq/mq-bridge/releases/download/v0.4.11/mq-bridge-cli-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "146d8abd7f39d0f83c7a2d46c9a0a66fd788c2c80951a41842370ac5907b1b11"
    end
    on_arm do
      url "https://github.com/marcomq/mq-bridge/releases/download/v0.4.11/mq-bridge-cli-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3590af60cf8b6ffe9d8b3ff2edc4fd0f90dbea7a370133cbef53a60ee61f1f49"
    end
  end

  def install
    # Both ship in the tarball: the real binary, plus the short `mqb` launcher
    # that forwards to it.
    bin.install "mq-bridge-app"
    bin.install "mqb"
    pkgshare.install "LICENSE", "THIRD_PARTY_LICENSES.txt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mq-bridge-app --version")
    assert_match version.to_s, shell_output("#{bin}/mqb --version")
  end
end
