# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh in marcomq/mq-bridge-pulsar — do not edit by hand.
class MqBridgePulsar < Formula
  desc "Apache Pulsar endpoint plugin for mq-bridge"
  homepage "https://github.com/marcomq/mq-bridge-pulsar"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/marcomq/mq-bridge-pulsar/releases/download/0.1.4/mq-bridge-pulsar-darwin-arm64.tar.gz"
      sha256 "c0795e496e003405d3f2fda623127989c9947813c8e60bdaa89a50cb33aedced"
    end
    on_intel do
      url "https://github.com/marcomq/mq-bridge-pulsar/releases/download/0.1.4/mq-bridge-pulsar-darwin-x64.tar.gz"
      sha256 "639b776a7a33149ec3bbb5a30f093bae2570abab20baccb482230bc359bdf61f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcomq/mq-bridge-pulsar/releases/download/0.1.4/mq-bridge-pulsar-linux-x64-gnu.tar.gz"
      sha256 "4dddb09adc152a322e89be55a3cffd3efc9c26806c57db53e9e261f114ff0754"
    end
    on_arm do
      url "https://github.com/marcomq/mq-bridge-pulsar/releases/download/0.1.4/mq-bridge-pulsar-linux-arm64-gnu.tar.gz"
      sha256 "38de5dd3052183cd7716baacb5519426c1e27a21a5b75c4c0bb912a834d40fd1"
    end
  end

  def install
    # $HOMEBREW_PREFIX/lib/mq-bridge is on mq-bridge's plugin search path.
    (lib/"mq-bridge").install Dir["libmq_bridge_pulsar.*"]
  end

  test do
    ext = OS.mac? ? "dylib" : "so"
    assert_predicate lib/"mq-bridge/libmq_bridge_pulsar.#{ext}", :exist?
  end
end
