# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh in marcomq/mq-bridge-meilisearch — do not edit by hand.
class MqBridgeMeilisearch < Formula
  desc "Meilisearch endpoint plugin for mq-bridge"
  homepage "https://github.com/marcomq/mq-bridge-meilisearch"
  version "0.1.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/marcomq/mq-bridge-meilisearch/releases/download/0.1.1/mq-bridge-meilisearch-0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "6050d1103e521b04841bf6ed3d6a2842452939302c0708732a8b77525a11dbf9"
    end
    on_intel do
      url "https://github.com/marcomq/mq-bridge-meilisearch/releases/download/0.1.1/mq-bridge-meilisearch-0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "fd8243cacebe8358360b40c55de7e982fb52e43dac350b350f9e6099891c3b01"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcomq/mq-bridge-meilisearch/releases/download/0.1.1/mq-bridge-meilisearch-0.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2c6fe58d8b052fa7963c623b055ea5460f88fa42a24e3c8860a9097482bb8d80"
    end
    on_arm do
      url "https://github.com/marcomq/mq-bridge-meilisearch/releases/download/0.1.1/mq-bridge-meilisearch-0.1.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "cd5fbab065d74c31ae122cf5f50679f73caa5400e0e42d9caf85db1d349387eb"
    end
  end

  def install
    # $HOMEBREW_PREFIX/lib/mq-bridge is on mq-bridge's plugin search path.
    (lib/"mq-bridge").install Dir["libmq_bridge_meilisearch.*"]
    doc.install "LICENSE-MIT", "LICENSE-APACHE"
  end

  test do
    ext = OS.mac? ? "dylib" : "so"
    assert_predicate lib/"mq-bridge/libmq_bridge_meilisearch.#{ext}", :exist?
  end
end
