# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh in marcomq/mq-bridge-meilisearch — do not edit by hand.
class MqBridgeMeilisearch < Formula
  desc "Meilisearch endpoint plugin for mq-bridge"
  homepage "https://github.com/marcomq/mq-bridge-meilisearch"
  version "0.1.2"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/marcomq/mq-bridge-meilisearch/releases/download/0.1.2/mq-bridge-meilisearch-0.1.2-aarch64-apple-darwin.tar.gz"
      sha256 "ab49327ea89a5d77d500fa316af18d11dc429f3ff355cd84d6e0acc19d228051"
    end
    on_intel do
      url "https://github.com/marcomq/mq-bridge-meilisearch/releases/download/0.1.2/mq-bridge-meilisearch-0.1.2-x86_64-apple-darwin.tar.gz"
      sha256 "eb8a2800d8258dc0c1a7ec2eb13616513c8478c786154af8e916e756b516b146"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcomq/mq-bridge-meilisearch/releases/download/0.1.2/mq-bridge-meilisearch-0.1.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "4df34f56977a4dc957c18584e8dd245044865b6460ee517ccf54044e46bb5f0e"
    end
    on_arm do
      url "https://github.com/marcomq/mq-bridge-meilisearch/releases/download/0.1.2/mq-bridge-meilisearch-0.1.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0b1105846a2fd1a8217c5c1a934fbac60fe346bdec3f9c701cd1d3dffac13db3"
    end
  end

  def install
    # $HOMEBREW_PREFIX/lib/mq-bridge is on mq-bridge's plugin search path.
    (lib/"mq-bridge").install Dir["libmq_bridge_meilisearch.*"]
    doc.install "LICENSE-MIT", "LICENSE-APACHE"
  end

  test do
    ext = OS.mac? ? "dylib" : "so"
    assert_predicate lib/"mq-bridge/libmq_bridge_meilisearch.#{ext}", :exist?
  end
end
