# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh in marcomq/mq-bridge-connect — do not edit by hand.
class MqBridgeConnect < Formula
  desc "Unofficial Redpanda Connect compatibility plugin for mq-bridge"
  homepage "https://github.com/marcomq/mq-bridge-connect"
  version "0.1.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/marcomq/mq-bridge-connect/releases/download/v0.1.1/mq-bridge-connect-0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "2d4dd2440692fb56754a372a08324267ea654756b81e1f0b216137b924911167"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcomq/mq-bridge-connect/releases/download/v0.1.1/mq-bridge-connect-0.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "caafa7ed9bcd574e9713519f6479fe9bfb5ed1d6de0fd5bfcbd47562193a5d7d"
    end
    on_arm do
      url "https://github.com/marcomq/mq-bridge-connect/releases/download/v0.1.1/mq-bridge-connect-0.1.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "58792ea82a6eec8fefe50ad92bd2f0acd06dfe4c1eeb6c8fac75c785091082b2"
    end
  end

  def install
    # Both libraries share one directory: the plugin loads its Go sibling from
    # beside itself. $HOMEBREW_PREFIX/lib/mq-bridge is on mq-bridge's search path.
    (lib/"mq-bridge").install Dir["libmq_bridge_connect*"]
    doc.install "THIRD_PARTY_NOTICES", "LICENSE-MIT", "LICENSE-APACHE", "INSTALL.md"
  end

  test do
    ext = OS.mac? ? "dylib" : "so"
    assert_predicate lib/"mq-bridge/libmq_bridge_connect.#{ext}", :exist?
    assert_predicate lib/"mq-bridge/libmq_bridge_connect_go.#{ext}", :exist?
    assert_predicate doc/"THIRD_PARTY_NOTICES", :exist?
  end
end
