# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh in marcomq/mq-bridge-connect — do not edit by hand.
class MqBridgeConnect < Formula
  desc "Unofficial Redpanda Connect compatibility plugin for mq-bridge"
  homepage "https://github.com/marcomq/mq-bridge-connect"
  version "0.1.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/marcomq/mq-bridge-connect/releases/download/v0.1.0/mq-bridge-connect-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "11f57efb1dc2229e8ac61fa639b5d89414b6578f3a8b5140b5de752e86495e2d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcomq/mq-bridge-connect/releases/download/v0.1.0/mq-bridge-connect-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9356a68aa25e77c00bae6191877994a75750fe184a74a45ba98039df7363c6fb"
    end
    on_arm do
      url "https://github.com/marcomq/mq-bridge-connect/releases/download/v0.1.0/mq-bridge-connect-0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3bd0866cc9b591cd01338af30b66f028aec8666259c2056cb231f10e2ba46100"
    end
  end

  def install
    # Both libraries share one directory: the plugin loads its Go sibling from
    # beside itself. $HOMEBREW_PREFIX/lib/mq-bridge is on mq-bridge's search path.
    (lib/"mq-bridge").install Dir["libmq_bridge_connect*"]
    doc.install "THIRD_PARTY_NOTICES", "LICENSE-MIT", "LICENSE-APACHE", "INSTALL.md"
  end

  test do
    ext = OS.mac? ? "dylib" : "so"
    assert_predicate lib/"mq-bridge/libmq_bridge_connect.#{ext}", :exist?
    assert_predicate lib/"mq-bridge/libmq_bridge_connect_go.#{ext}", :exist?
    assert_predicate doc/"THIRD_PARTY_NOTICES", :exist?
  end
end
