# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh — do not edit by hand.
class MqBridgeApp < Formula
  desc "Universal, protocol-agnostic message and data bridge (CLI + MCP server)"
  homepage "https://github.com/marcomq/mq-bridge"
  version "0.4.17"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/marcomq/mq-bridge/releases/download/v0.4.17/mq-bridge-cli-aarch64-apple-darwin.tar.gz"
      sha256 "2d87b2442c88f657cbb0d36d89d8e335d223ab8c9a759f03a72a5bdeed800690"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcomq/mq-bridge/releases/download/v0.4.17/mq-bridge-cli-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f4fc6bbc40fc5086a5dc8dfacdafc99cbae4d166458cedc12a15fd9198cc9d3d"
    end
    on_arm do
      url "https://github.com/marcomq/mq-bridge/releases/download/v0.4.17/mq-bridge-cli-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0dbc2f199c57ce93d0f965605ca86150cde82af16896667496eef3ba862fa236"
    end
  end

  def install
    # Both ship in the tarball: the real binary, plus the short `mqb` launcher
    # that forwards to it.
    bin.install "mq-bridge-app"
    bin.install "mqb"
    pkgshare.install "LICENSE", "LICENSE-MIT", "LICENSE-APACHE", "THIRD_PARTY_LICENSES.txt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mq-bridge-app --version")
    assert_match version.to_s, shell_output("#{bin}/mqb --version")
  end
end
